*** Starting uWSGI 2.0.19.1 (64bit) on [Sun Mar 28 22:44:14 2021] ***
compiled with version: 7.5.0 on 28 March 2021 21:55:47
os: Linux-5.4.0-1040-gcp #43~18.04.1-Ubuntu SMP Sat Mar 20 14:37:40 UTC 2021
nodename: ttds-main
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/moyuhao/ttds
detected binary path: /home/moyuhao/ttds/venv/bin/uwsgi
chdir() to /home/moyuhao/ttds
your processes number limit is 31671
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :5000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:41211 (port auto-assigned) fd 3
Python version: 3.6.9 (default, Jan 26 2021, 15:33:00)  [GCC 8.4.0]
Python main interpreter initialized at 0x55bb7fa475a0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416720 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55bb7fa475a0 pid: 2863 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2863)
spawned uWSGI worker 1 (pid: 2865, cores: 2)
spawned uWSGI worker 2 (pid: 2866, cores: 2)
spawned uWSGI worker 3 (pid: 2867, cores: 2)
spawned uWSGI worker 4 (pid: 2869, cores: 2)
spawned uWSGI http 1 (pid: 2870)
[pid: 2867|app: 0|req: 1/1] 31.205.104.216 () {36 vars in 625 bytes} [Sun Mar 28 22:44:28 2021] GET / => generated 856 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 2867|app: 0|req: 2/2] 31.205.104.216 () {40 vars in 718 bytes} [Sun Mar 28 22:44:28 2021] GET /static/index.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 182 bytes (0 switches on core 1)
[pid: 2866|app: 0|req: 1/3] 31.205.104.216 () {40 vars in 734 bytes} [Sun Mar 28 22:44:28 2021] GET /static/image.jpg => generated 0 bytes in 2 msecs (HTTP/1.1 304) 4 headers in 186 bytes (0 switches on core 0)
[pid: 2866|app: 0|req: 2/4] 31.205.104.216 () {36 vars in 625 bytes} [Sun Mar 28 22:45:09 2021] GET / => generated 856 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 1)
[pid: 2866|app: 0|req: 3/5] 31.205.104.216 () {40 vars in 718 bytes} [Sun Mar 28 22:45:09 2021] GET /static/index.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 182 bytes (0 switches on core 0)
[pid: 2865|app: 0|req: 1/6] 31.205.104.216 () {40 vars in 734 bytes} [Sun Mar 28 22:45:09 2021] GET /static/image.jpg => generated 0 bytes in 2 msecs (HTTP/1.1 304) 4 headers in 186 bytes (0 switches on core 0)
[pid: 2865|app: 0|req: 2/7] 61.151.207.112 () {32 vars in 480 bytes} [Sun Mar 28 22:45:17 2021] GET / => generated 856 bytes in 6 msecs (HTTP/1.0 200) 2 headers in 80 bytes (1 switches on core 1)
[pid: 2865|app: 0|req: 3/8] 31.205.104.216 () {36 vars in 597 bytes} [Sun Mar 28 22:45:39 2021] GET / => generated 856 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 2869|app: 0|req: 1/9] 31.205.104.216 () {36 vars in 590 bytes} [Sun Mar 28 22:45:40 2021] GET /static/index.css => generated 787 bytes in 2 msecs via sendfile() (HTTP/1.1 200) 7 headers in 278 bytes (0 switches on core 0)
[pid: 2869|app: 0|req: 2/10] 31.205.104.216 () {36 vars in 644 bytes} [Sun Mar 28 22:45:40 2021] GET /static/image.jpg => generated 1125144 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 273 bytes (0 switches on core 1)
[pid: 2869|app: 0|req: 3/11] 31.205.104.216 () {36 vars in 565 bytes} [Sun Mar 28 22:45:41 2021] GET /favicon.ico => generated 232 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 0)
[pid: 2867|app: 0|req: 3/12] 192.41.114.225 () {34 vars in 670 bytes} [Sun Mar 28 22:45:57 2021] GET / => generated 856 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 2867|app: 0|req: 4/13] 192.41.114.225 () {36 vars in 676 bytes} [Sun Mar 28 22:45:58 2021] GET /static/index.css => generated 787 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 278 bytes (0 switches on core 1)
[pid: 2869|app: 0|req: 4/14] 192.41.114.225 () {36 vars in 702 bytes} [Sun Mar 28 22:45:58 2021] GET /static/image.jpg => generated 1125144 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 273 bytes (0 switches on core 1)
[pid: 2869|app: 0|req: 5/15] 192.41.114.225 () {36 vars in 676 bytes} [Sun Mar 28 22:45:59 2021] GET /favicon.ico => generated 232 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 0)
[pid: 2866|app: 0|req: 4/16] 31.205.104.216 () {36 vars in 625 bytes} [Sun Mar 28 22:46:15 2021] GET / => generated 856 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 1)
[pid: 2866|app: 0|req: 5/17] 31.205.104.216 () {40 vars in 718 bytes} [Sun Mar 28 22:46:15 2021] GET /static/index.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 182 bytes (0 switches on core 0)
[pid: 2867|app: 0|req: 5/18] 31.205.104.216 () {40 vars in 734 bytes} [Sun Mar 28 22:46:15 2021] GET /static/image.jpg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 186 bytes (0 switches on core 1)
[pid: 2867|app: 0|req: 6/19] 61.129.6.251 () {32 vars in 601 bytes} [Sun Mar 28 22:46:17 2021] GET / => generated 856 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 2865|app: 0|req: 4/20] 31.205.104.216 () {36 vars in 597 bytes} [Sun Mar 28 22:47:01 2021] GET / => generated 856 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 2867|app: 0|req: 7/21] 31.205.104.216 () {40 vars in 701 bytes} [Sun Mar 28 22:47:01 2021] GET /static/index.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 182 bytes (0 switches on core 1)
[pid: 2869|app: 0|req: 6/22] 31.205.104.216 () {40 vars in 759 bytes} [Sun Mar 28 22:47:01 2021] GET /static/image.jpg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 186 bytes (0 switches on core 1)
[pid: 2865|app: 0|req: 5/23] 213.205.194.2 () {34 vars in 669 bytes} [Sun Mar 28 22:47:31 2021] GET / => generated 856 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 2869|app: 0|req: 7/24] 213.205.194.2 () {40 vars in 786 bytes} [Sun Mar 28 22:47:31 2021] GET /static/index.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 182 bytes (0 switches on core 0)
[pid: 2865|app: 0|req: 6/25] 213.205.194.2 () {40 vars in 816 bytes} [Sun Mar 28 22:47:32 2021] GET /static/image.jpg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 186 bytes (0 switches on core 1)
[pid: 2865|app: 0|req: 7/26] 213.205.194.2 () {36 vars in 675 bytes} [Sun Mar 28 22:47:33 2021] GET /favicon.ico => generated 232 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 0)
[pid: 2869|app: 0|req: 8/27] 31.205.104.216 () {36 vars in 597 bytes} [Sun Mar 28 22:53:32 2021] GET / => generated 856 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 1)
[pid: 2867|app: 0|req: 9/28] 31.205.104.216 () {40 vars in 701 bytes} [Sun Mar 28 22:53:32 2021] GET /static/index.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 182 bytes (0 switches on core 0)
[pid: 2867|app: 0|req: 9/29] 31.205.104.216 () {40 vars in 759 bytes} [Sun Mar 28 22:53:32 2021] GET /static/image.jpg => generated 0 bytes in 0 msecs (HTTP/1.1 304) 4 headers in 186 bytes (0 switches on core 1)
[pid: 2866|app: 0|req: 6/30] 31.205.104.216 () {40 vars in 701 bytes} [Sun Mar 28 22:53:32 2021] GET /static/index.css => generated 0 bytes in 0 msecs (HTTP/1.1 304) 4 headers in 182 bytes (0 switches on core 1)
[pid: 2866|app: 0|req: 7/31] 31.205.104.216 () {40 vars in 759 bytes} [Sun Mar 28 22:53:32 2021] GET /static/image.jpg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 186 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Sun Mar 28 22:54:36 2021] ***
compiled with version: 7.5.0 on 28 March 2021 21:49:50
os: Linux-5.4.0-1040-gcp #43~18.04.1-Ubuntu SMP Sat Mar 20 14:37:40 UTC 2021
nodename: ttds-main
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/moyuhao/ttds
detected binary path: /home/moyuhao/.local/bin/uwsgi
chdir() to /home/moyuhao/ttds
your processes number limit is 31671
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :5000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:41645 (port auto-assigned) fd 3
Python version: 2.7.17 (default, Feb 27 2021, 15:10:58)  [GCC 7.5.0]
Python main interpreter initialized at 0x5618ff3540d0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416720 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x5618ff3540d0 pid: 3104 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3104)
spawned uWSGI worker 1 (pid: 3106, cores: 2)
spawned uWSGI worker 2 (pid: 3107, cores: 2)
spawned uWSGI worker 3 (pid: 3108, cores: 2)
spawned uWSGI worker 4 (pid: 3109, cores: 2)
spawned uWSGI http 1 (pid: 3110)
[pid: 3109|app: 0|req: 1/1] 31.205.104.216 () {36 vars in 625 bytes} [Sun Mar 28 22:54:50 2021] GET / => generated 859 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 3106|app: 0|req: 1/2] 31.205.104.216 () {40 vars in 718 bytes} [Sun Mar 28 22:54:50 2021] GET /static/index.css => generated 787 bytes in 5 msecs via sendfile() (HTTP/1.1 200) 7 headers in 273 bytes (0 switches on core 0)
[pid: 3106|app: 0|req: 2/3] 31.205.104.216 () {40 vars in 734 bytes} [Sun Mar 28 22:54:51 2021] GET /static/image.jpg => generated 1125144 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 268 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 19, in search
    return render_template('music.html', result=algorithm('song', query), search_keyword = query)
  File "./app/algorithm.py", line 249, in algorithm
    title = pickle.load(f)
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 4
[pid: 3109|app: 0|req: 2/4] 31.205.104.216 () {44 vars in 787 bytes} [Sun Mar 28 22:54:54 2021] POST /search => generated 0 bytes in 10 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 19, in search
    return render_template('music.html', result=algorithm('song', query), search_keyword = query)
  File "./app/algorithm.py", line 249, in algorithm
    title = pickle.load(f)
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 4
[pid: 3106|app: 0|req: 3/5] 31.205.104.216 () {44 vars in 787 bytes} [Sun Mar 28 22:55:04 2021] POST /search => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
[pid: 3109|app: 0|req: 3/6] 31.205.104.216 () {36 vars in 597 bytes} [Sun Mar 28 22:55:09 2021] GET / => generated 859 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 3106|app: 0|req: 4/7] 31.205.104.216 () {40 vars in 701 bytes} [Sun Mar 28 22:55:10 2021] GET /static/index.css => generated 787 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 273 bytes (0 switches on core 1)
[pid: 3109|app: 0|req: 4/8] 31.205.104.216 () {40 vars in 759 bytes} [Sun Mar 28 22:55:10 2021] GET /static/image.jpg => generated 1125144 bytes in 4 msecs via sendfile() (HTTP/1.1 200) 7 headers in 268 bytes (0 switches on core 1)
[pid: 3108|app: 0|req: 1/9] 31.205.104.216 () {40 vars in 701 bytes} [Sun Mar 28 22:55:10 2021] GET /static/index.css => generated 787 bytes in 4 msecs via sendfile() (HTTP/1.1 200) 7 headers in 273 bytes (0 switches on core 0)
[pid: 3107|app: 0|req: 1/10] 31.205.104.216 () {40 vars in 759 bytes} [Sun Mar 28 22:55:11 2021] GET /static/image.jpg => generated 1125144 bytes in 5 msecs via sendfile() (HTTP/1.1 200) 7 headers in 268 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 19, in search
    return render_template('music.html', result=algorithm('song', query), search_keyword = query)
  File "./app/algorithm.py", line 249, in algorithm
    title = pickle.load(f)
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 4
[pid: 3109|app: 0|req: 5/11] 31.205.104.216 () {44 vars in 759 bytes} [Sun Mar 28 22:55:14 2021] POST /search => generated 0 bytes in 3 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/.local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3109|app: 0|req: 6/12] 31.205.104.216 () {36 vars in 609 bytes} [Sun Mar 28 22:55:28 2021] GET /search => generated 0 bytes in 3 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/.local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3106|app: 0|req: 5/13] 31.205.104.216 () {36 vars in 609 bytes} [Sun Mar 28 22:55:28 2021] GET /search => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/.local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3106|app: 0|req: 6/14] 31.205.104.216 () {36 vars in 609 bytes} [Sun Mar 28 22:55:28 2021] GET /search => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/.local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3109|app: 0|req: 7/15] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 22:55:32 2021] GET /search => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/.local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3107|app: 0|req: 2/16] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 22:55:32 2021] GET /search => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/.local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3107|app: 0|req: 3/17] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 22:55:32 2021] GET /search => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/.local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3106|app: 0|req: 7/18] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 22:55:33 2021] GET /search => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/.local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3108|app: 0|req: 2/19] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 22:55:33 2021] GET /search => generated 0 bytes in 3 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/.local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3108|app: 0|req: 3/20] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 22:55:33 2021] GET /search => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/.local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3106|app: 0|req: 8/21] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 22:55:33 2021] GET /search => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/.local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3107|app: 0|req: 4/22] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 22:55:33 2021] GET /search => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/.local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3107|app: 0|req: 5/23] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 22:55:34 2021] GET /search => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/.local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3109|app: 0|req: 8/24] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 22:55:34 2021] GET /search => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
[pid: 3109|app: 0|req: 9/25] 31.205.104.216 () {36 vars in 625 bytes} [Sun Mar 28 22:55:36 2021] GET / => generated 859 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 3106|app: 0|req: 9/26] 31.205.104.216 () {40 vars in 713 bytes} [Sun Mar 28 22:55:36 2021] GET /static/index.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 177 bytes (0 switches on core 0)
[pid: 3106|app: 0|req: 10/27] 31.205.104.216 () {40 vars in 729 bytes} [Sun Mar 28 22:55:36 2021] GET /static/image.jpg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 181 bytes (0 switches on core 1)
[pid: 3109|app: 0|req: 10/28] 31.205.104.216 () {36 vars in 625 bytes} [Sun Mar 28 22:56:35 2021] GET / => generated 859 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 1)
[pid: 3106|app: 0|req: 11/29] 31.205.104.216 () {40 vars in 713 bytes} [Sun Mar 28 22:56:35 2021] GET /static/index.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 177 bytes (0 switches on core 0)
[pid: 3106|app: 0|req: 12/30] 31.205.104.216 () {40 vars in 729 bytes} [Sun Mar 28 22:56:36 2021] GET /static/image.jpg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 181 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 19, in search
    return render_template('music.html', result=algorithm('song', query), search_keyword = query)
  File "./app/algorithm.py", line 249, in algorithm
    title = pickle.load(f)
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 4
[pid: 3107|app: 0|req: 6/31] 31.205.104.216 () {44 vars in 787 bytes} [Sun Mar 28 22:56:39 2021] POST /search => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
*** Starting uWSGI 2.0.19.1 (64bit) on [Sun Mar 28 22:56:51 2021] ***
compiled with version: 7.5.0 on 28 March 2021 21:49:50
os: Linux-5.4.0-1040-gcp #43~18.04.1-Ubuntu SMP Sat Mar 20 14:37:40 UTC 2021
nodename: ttds-main
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/moyuhao/ttds
detected binary path: /home/moyuhao/.local/bin/uwsgi
chdir() to /home/moyuhao/ttds
your processes number limit is 31671
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :5000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:42859 (port auto-assigned) fd 3
Python version: 2.7.17 (default, Feb 27 2021, 15:10:58)  [GCC 7.5.0]
Python main interpreter initialized at 0x558f3db2b0d0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416720 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x558f3db2b0d0 pid: 3154 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3154)
spawned uWSGI worker 1 (pid: 3156, cores: 2)
spawned uWSGI worker 2 (pid: 3157, cores: 2)
spawned uWSGI worker 3 (pid: 3158, cores: 2)
spawned uWSGI worker 4 (pid: 3159, cores: 2)
spawned uWSGI http 1 (pid: 3160)
[pid: 3159|app: 0|req: 1/1] 31.205.104.216 () {36 vars in 625 bytes} [Sun Mar 28 22:56:56 2021] GET / => generated 859 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 3156|app: 0|req: 1/2] 31.205.104.216 () {40 vars in 713 bytes} [Sun Mar 28 22:56:56 2021] GET /static/index.css => generated 0 bytes in 5 msecs (HTTP/1.1 304) 4 headers in 177 bytes (0 switches on core 0)
[pid: 3156|app: 0|req: 2/3] 31.205.104.216 () {40 vars in 729 bytes} [Sun Mar 28 22:56:56 2021] GET /static/image.jpg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 181 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 19, in search
    return render_template('music.html', result=algorithm('song', query), search_keyword = query)
  File "./app/algorithm.py", line 249, in algorithm
    title = pickle.load(f)
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 4
[pid: 3157|app: 0|req: 1/4] 31.205.104.216 () {44 vars in 787 bytes} [Sun Mar 28 22:57:00 2021] POST /search => generated 0 bytes in 3 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/.local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3159|app: 0|req: 2/5] 31.205.104.216 () {36 vars in 609 bytes} [Sun Mar 28 22:57:10 2021] GET /search => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/.local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3157|app: 0|req: 2/6] 31.205.104.216 () {36 vars in 609 bytes} [Sun Mar 28 22:57:10 2021] GET /search => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/.local/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/.local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3158|app: 0|req: 1/7] 31.205.104.216 () {36 vars in 609 bytes} [Sun Mar 28 22:57:10 2021] GET /search => generated 0 bytes in 3 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Sun Mar 28 23:00:51 2021] ***
compiled with version: 7.5.0 on 28 March 2021 21:55:47
os: Linux-5.4.0-1040-gcp #43~18.04.1-Ubuntu SMP Sat Mar 20 14:37:40 UTC 2021
nodename: ttds-main
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/moyuhao/ttds
detected binary path: /home/moyuhao/ttds/venv/bin/uwsgi
chdir() to /home/moyuhao/ttds
your processes number limit is 31671
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :5000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:45489 (port auto-assigned) fd 3
Python version: 3.6.9 (default, Jan 26 2021, 15:33:00)  [GCC 8.4.0]
Python main interpreter initialized at 0x56125ad5b5a0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416720 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x56125ad5b5a0 pid: 3247 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3247)
spawned uWSGI worker 1 (pid: 3249, cores: 2)
spawned uWSGI worker 2 (pid: 3250, cores: 2)
spawned uWSGI worker 3 (pid: 3251, cores: 2)
spawned uWSGI worker 4 (pid: 3253, cores: 2)
spawned uWSGI http 1 (pid: 3254)
[pid: 3251|app: 0|req: 1/1] 31.205.104.216 () {36 vars in 625 bytes} [Sun Mar 28 23:00:55 2021] GET / => generated 859 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 3251|app: 0|req: 2/2] 31.205.104.216 () {40 vars in 718 bytes} [Sun Mar 28 23:00:56 2021] GET /static/index.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 182 bytes (0 switches on core 1)
[pid: 3250|app: 0|req: 1/3] 31.205.104.216 () {40 vars in 734 bytes} [Sun Mar 28 23:00:56 2021] GET /static/image.jpg => generated 0 bytes in 3 msecs (HTTP/1.1 304) 4 headers in 186 bytes (0 switches on core 0)
[pid: 3250|app: 0|req: 2/4] 31.205.104.216 () {44 vars in 787 bytes} [Sun Mar 28 23:01:01 2021] POST /search => generated 2708 bytes in 1932 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 1)
[pid: 3249|app: 0|req: 1/5] 31.205.104.216 () {40 vars in 725 bytes} [Sun Mar 28 23:01:03 2021] GET /static/music.css => generated 0 bytes in 2 msecs (HTTP/1.1 304) 4 headers in 183 bytes (0 switches on core 0)
[pid: 3249|app: 0|req: 2/6] 31.205.104.197 () {36 vars in 613 bytes} [Sun Mar 28 23:01:44 2021] GET / => generated 859 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 1)
[pid: 3250|app: 0|req: 3/7] 31.205.104.197 () {36 vars in 606 bytes} [Sun Mar 28 23:01:45 2021] GET /static/index.css => generated 787 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 278 bytes (0 switches on core 0)
[pid: 3249|app: 0|req: 3/8] 31.205.104.197 () {36 vars in 660 bytes} [Sun Mar 28 23:01:45 2021] GET /static/image.jpg => generated 1125144 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 273 bytes (0 switches on core 0)
[pid: 3249|app: 0|req: 4/9] 31.205.104.197 () {36 vars in 581 bytes} [Sun Mar 28 23:01:48 2021] GET /favicon.ico => generated 232 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 1)
[pid: 3253|app: 0|req: 1/10] 31.205.104.197 () {36 vars in 613 bytes} [Sun Mar 28 23:01:49 2021] GET / => generated 859 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 3249|app: 0|req: 5/11] 31.205.104.197 () {40 vars in 717 bytes} [Sun Mar 28 23:01:49 2021] GET /static/index.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 182 bytes (0 switches on core 0)
[pid: 3251|app: 0|req: 3/12] 31.205.104.197 () {40 vars in 775 bytes} [Sun Mar 28 23:01:49 2021] GET /static/image.jpg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 186 bytes (0 switches on core 0)
[pid: 3250|app: 0|req: 4/13] 31.205.104.197 () {44 vars in 775 bytes} [Sun Mar 28 23:02:00 2021] POST /search => generated 2709 bytes in 1732 msecs (HTTP/1.1 200) 2 headers in 81 bytes (2 switches on core 0)
[pid: 3250|app: 0|req: 5/14] 31.205.104.197 () {36 vars in 612 bytes} [Sun Mar 28 23:02:02 2021] GET /static/music.css => generated 2406 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 280 bytes (0 switches on core 1)
[pid: 3251|app: 0|req: 4/15] 31.205.104.197 () {36 vars in 587 bytes} [Sun Mar 28 23:02:02 2021] GET /favicon.ico => generated 232 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 1)
[pid: 3249|app: 0|req: 6/16] 213.205.194.2 () {36 vars in 687 bytes} [Sun Mar 28 23:02:53 2021] GET /favicon.ico => generated 232 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 1)
[pid: 3249|app: 0|req: 7/17] 213.205.194.2 () {34 vars in 681 bytes} [Sun Mar 28 23:02:56 2021] GET / => generated 859 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 3253|app: 0|req: 2/18] 213.205.194.2 () {40 vars in 798 bytes} [Sun Mar 28 23:02:56 2021] GET /static/index.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 182 bytes (0 switches on core 1)
[pid: 3250|app: 0|req: 6/19] 213.205.194.2 () {36 vars in 687 bytes} [Sun Mar 28 23:02:56 2021] GET /favicon.ico => generated 232 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 0)
[pid: 3253|app: 0|req: 3/20] 31.205.104.203 () {36 vars in 682 bytes} [Sun Mar 28 23:03:05 2021] GET / => generated 859 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 1)
[pid: 3253|app: 0|req: 4/21] 31.205.104.203 () {36 vars in 603 bytes} [Sun Mar 28 23:03:05 2021] GET /static/index.css => generated 787 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 278 bytes (0 switches on core 0)
[pid: 3253|app: 0|req: 5/22] 31.205.104.203 () {36 vars in 665 bytes} [Sun Mar 28 23:03:05 2021] GET /static/image.jpg => generated 1125144 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 273 bytes (0 switches on core 0)
[pid: 3251|app: 0|req: 5/23] 213.205.194.2 () {44 vars in 874 bytes} [Sun Mar 28 23:03:04 2021] POST /search => generated 846 bytes in 1924 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 3251|app: 0|req: 6/24] 213.205.194.2 () {36 vars in 693 bytes} [Sun Mar 28 23:03:06 2021] GET /static/music.css => generated 2406 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 280 bytes (0 switches on core 1)
[pid: 3250|app: 0|req: 7/25] 31.205.104.203 () {36 vars in 639 bytes} [Sun Mar 28 23:03:07 2021] GET /favicon.ico => generated 232 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 1)
[pid: 3249|app: 0|req: 8/26] 31.205.104.203 () {46 vars in 875 bytes} [Sun Mar 28 23:03:10 2021] POST /search => generated 846 bytes in 1961 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 1)
[pid: 3249|app: 0|req: 9/27] 31.205.104.203 () {36 vars in 609 bytes} [Sun Mar 28 23:03:13 2021] GET /static/music.css => generated 2406 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 280 bytes (0 switches on core 0)
[pid: 3253|app: 0|req: 6/28] 213.205.194.2 () {44 vars in 880 bytes} [Sun Mar 28 23:03:25 2021] POST /search => generated 846 bytes in 1934 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 3251|app: 0|req: 7/29] 213.205.194.2 () {40 vars in 805 bytes} [Sun Mar 28 23:03:27 2021] GET /static/music.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 183 bytes (0 switches on core 0)
[pid: 3251|app: 0|req: 8/30] 213.205.194.2 () {44 vars in 880 bytes} [Sun Mar 28 23:03:34 2021] POST /search => generated 2708 bytes in 1758 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 1)
[pid: 3250|app: 0|req: 8/31] 213.205.194.2 () {40 vars in 805 bytes} [Sun Mar 28 23:03:37 2021] GET /static/music.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 183 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3253|app: 0|req: 7/32] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 23:07:41 2021] GET /search => generated 0 bytes in 10 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3250|app: 0|req: 9/33] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 23:07:41 2021] GET /search => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3250|app: 0|req: 10/34] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 23:07:41 2021] GET /search => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3249|app: 0|req: 10/35] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 23:07:42 2021] GET /search => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3253|app: 0|req: 8/36] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 23:07:42 2021] GET /search => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3253|app: 0|req: 9/37] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 23:07:42 2021] GET /search => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3249|app: 0|req: 11/38] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 23:07:42 2021] GET /search => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3251|app: 0|req: 9/39] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 23:07:42 2021] GET /search => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3249|app: 0|req: 12/40] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 23:07:43 2021] GET /search => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3251|app: 0|req: 10/41] 31.205.104.216 () {36 vars in 637 bytes} [Sun Mar 28 23:07:43 2021] GET /search => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
[pid: 3249|app: 0|req: 13/42] 31.205.104.216 () {36 vars in 625 bytes} [Sun Mar 28 23:07:46 2021] GET / => generated 859 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 3249|app: 0|req: 14/43] 31.205.104.216 () {40 vars in 718 bytes} [Sun Mar 28 23:07:46 2021] GET /static/index.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 182 bytes (0 switches on core 1)
[pid: 3251|app: 0|req: 11/44] 31.205.104.216 () {40 vars in 734 bytes} [Sun Mar 28 23:07:46 2021] GET /static/image.jpg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 186 bytes (0 switches on core 0)
[pid: 3251|app: 0|req: 12/45] 31.205.104.216 () {44 vars in 787 bytes} [Sun Mar 28 23:07:51 2021] POST /search => generated 2708 bytes in 1913 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 1)
[pid: 3249|app: 0|req: 15/46] 31.205.104.216 () {40 vars in 725 bytes} [Sun Mar 28 23:07:53 2021] GET /static/music.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 183 bytes (0 switches on core 0)
[pid: 3253|app: 0|req: 10/47] 180.125.126.10 () {38 vars in 933 bytes} [Sun Mar 28 23:24:05 2021] GET / => generated 859 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 1)
[pid: 3249|app: 0|req: 16/48] 180.125.126.10 () {38 vars in 849 bytes} [Sun Mar 28 23:24:05 2021] GET /static/index.css => generated 787 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 278 bytes (0 switches on core 1)
[pid: 3249|app: 0|req: 17/49] 180.125.126.10 () {38 vars in 930 bytes} [Sun Mar 28 23:24:06 2021] GET /static/image.jpg => generated 1125144 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 7 headers in 273 bytes (0 switches on core 0)
[pid: 3249|app: 0|req: 18/50] 180.125.126.10 () {38 vars in 904 bytes} [Sun Mar 28 23:24:08 2021] GET /favicon.ico => generated 232 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 1)
[pid: 3253|app: 0|req: 11/51] 180.125.126.10 () {38 vars in 953 bytes} [Sun Mar 28 23:24:19 2021] GET /music.html => generated 232 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 1)
[pid: 3249|app: 0|req: 19/52] 180.125.126.10 () {38 vars in 933 bytes} [Sun Mar 28 23:25:05 2021] GET / => generated 859 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 3253|app: 0|req: 12/53] 180.125.126.10 () {42 vars in 960 bytes} [Sun Mar 28 23:25:05 2021] GET /static/index.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 182 bytes (0 switches on core 0)
[pid: 3250|app: 0|req: 11/54] 180.125.126.10 () {42 vars in 1045 bytes} [Sun Mar 28 23:25:06 2021] GET /static/image.jpg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 186 bytes (0 switches on core 1)
[pid: 3249|app: 0|req: 20/55] 180.125.126.10 () {38 vars in 904 bytes} [Sun Mar 28 23:25:06 2021] GET /favicon.ico => generated 232 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 1)
[pid: 3250|app: 0|req: 12/56] 180.125.126.10 () {38 vars in 953 bytes} [Sun Mar 28 23:25:16 2021] GET /music.html => generated 232 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 0)
[pid: 3250|app: 0|req: 13/57] 61.151.179.84 () {32 vars in 550 bytes} [Sun Mar 28 23:25:17 2021] GET /music.html => generated 232 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 1)
Traceback (most recent call last):
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3250|app: 0|req: 14/58] 192.41.114.225 () {42 vars in 832 bytes} [Sun Mar 28 23:26:25 2021] POST /search => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/search.py", line 17, in search
    query = request.form['keyword']
  File "/home/moyuhao/ttds/venv/lib/python3.6/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'keyword'
[pid: 3250|app: 0|req: 15/59] 192.41.114.225 () {42 vars in 832 bytes} [Sun Mar 28 23:26:26 2021] POST /search => generated 0 bytes in 6 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
